apiVersion: v1
kind: Service # web-browser -> Service -> Pod
metadata:
  name: demo
  labels:
    app: demo
spec:
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 8888
  selector: #rotea para o Pod
    app: demo
  type: ClusterIP

  
