

---
apiVersion: v1
kind: Pod
#...
spec: 
  
  volumes:
  - name: cache-volume #volume compartilhado por container neste Pod 
    emptyDir: {} #persistência enquanto Pod executando
  
  containers:
  - name: demo
    image: cloudnatived/demo:hello
    volumeMounts:
    - mountPath: /cache
      name: cache-volume #volume criado





...